import { Division } from "@/types";

export const divisions: Division[] = [
  {
    id: "interior",
    name: "Interior Paints",
    shortName: "Interior",
    description: "Emulsions, textures, and finishes for walls, ceilings, and living spaces",
    icon: "🏠",
    color: "navy",
    href: "/#contact",
  },
  {
    id: "exterior",
    name: "Exterior Paints",
    shortName: "Exterior",
    description: "UV-resistant coatings for monsoon, heat, and long-term protection",
    icon: "🌤️",
    color: "magenta",
    href: "/#contact",
  },
  {
    id: "waterproofing",
    name: "Waterproofing",
    shortName: "Waterproofing",
    description: "Terrace, bathroom, and foundation protection from leaks and damp",
    icon: "💧",
    color: "yellow",
    href: "/#contact",
  },
  {
    id: "wood",
    name: "Wood Coatings",
    shortName: "Wood",
    description: "PU, Duco, melamine, and stains for furniture and interior wood",
    icon: "🪵",
    color: "navy",
    href: "/#contact",
  },
  {
    id: "industrial",
    name: "Industrial Solutions",
    shortName: "Industrial",
    description: "Epoxy floors, machinery coatings, and factory-grade finishes",
    icon: "🏭",
    color: "magenta",
    href: "/#contact",
  },
  {
    id: "automotive",
    name: "Automotive Paints",
    shortName: "Automotive",
    description: "Metallic finishes, anti-rust primers, and colour matching for vehicles",
    icon: "🚗",
    color: "yellow",
    href: "/#contact",
  },
  {
    id: "textures",
    name: "Textures & Mineral",
    shortName: "Textures",
    description: "Designer effects, stone looks, and eco-friendly mineral coatings",
    icon: "✨",
    color: "navy",
    href: "/#contact",
  },
  {
    id: "services",
    name: "Painting Services",
    shortName: "Services",
    description: "Professional application, site visits, and quality guarantees",
    icon: "👷",
    color: "magenta",
    href: "/#contact",
  },
  {
    id: "ai-expert",
    name: "AI Paint Expert",
    shortName: "AI Expert",
    description: "Real-time paint consultation powered by AI, 24/7 support",
    icon: "🤖",
    color: "yellow",
    href: "/chatbot",
  },
];
